In [1]:
import numpy as np

In [7]:
f_array = np.arange(1, 11)
print(f_array)
s_array = np.arange(0.5, 5 + 0.1, 0.5)
print(s_array) 

[ 1  2  3  4  5  6  7  8  9 10]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [13]:
print(np.zeros(10))
print(np.zeros(shape=(3,4))) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
t_array = np.linspace(2,12,5)
print(t_array)
f_array = np.linspace(3,9,4)


[ 2.   4.5  7.   9.5 12. ]


In [43]:
e_array = np.random.rand(4,2)
print(e_array)
b_array = e_array.reshape(1,8)
print(b_array)
n_array = np.random.randint(10,20,(3,3))
print(n_array)


[[0.51913607 0.0536034 ]
 [0.01288718 0.33729239]
 [0.91868871 0.64977829]
 [0.72071652 0.9223428 ]]
[[0.51913607 0.0536034  0.01288718 0.33729239 0.91868871 0.64977829
  0.72071652 0.9223428 ]]
[[11 12 15]
 [15 16 19]
 [18 13 11]]


In [47]:
####In reshape we have to check that the number of items in perfectly the same

In [49]:
####If we use seed in random actions within every session we'll get the same random numbers,
####which is usefull in tests and simulations

# 